# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_info',
            old_name='Company_name',
            new_name='name',
        ),
    ]
