# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexun', '0002_auto_20170410_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dongshihui_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801')),
                ('dongjiangao', models.CharField(default='-', max_length=255, verbose_name='\u8463\u76d1\u9ad8\u59d3\u540d')),
                ('gaoguanzhiwu', models.CharField(default='-', max_length=255, verbose_name='\u9ad8\u7ba1\u804c\u52a1')),
                ('renzhiriqi', models.CharField(default='-', max_length=255, verbose_name='\u4efb\u804c\u65e5\u671f')),
                ('lizhiriqi', models.CharField(default='-', max_length=255, verbose_name='\u79bb\u804c\u65e5\u671f')),
                ('xueli', models.CharField(default='-', max_length=255, verbose_name='\u5b66\u5386')),
                ('nianxin', models.CharField(default='-', max_length=255, verbose_name='\u5e74\u85aa(\u4e07\u5143)')),
                ('chiguzonge', models.CharField(default='-', max_length=255, verbose_name='\u6301\u80a1\u603b\u989d(\u4e07\u5143)')),
                ('chigushuliang', models.CharField(default='-', max_length=255, verbose_name='\u6301\u80a1\u6570\u91cf(\u4e07\u80a1)')),
            ],
        ),
        migrations.CreateModel(
            name='Jianshihui_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801')),
                ('dongjiangao', models.CharField(default='-', max_length=255, verbose_name='\u8463\u76d1\u9ad8\u59d3\u540d')),
                ('gaoguanzhiwu', models.CharField(default='-', max_length=255, verbose_name='\u9ad8\u7ba1\u804c\u52a1')),
                ('renzhiriqi', models.CharField(default='-', max_length=255, verbose_name='\u4efb\u804c\u65e5\u671f')),
                ('lizhiriqi', models.CharField(default='-', max_length=255, verbose_name='\u79bb\u804c\u65e5\u671f')),
                ('xueli', models.CharField(default='-', max_length=255, verbose_name='\u5b66\u5386')),
                ('nianxin', models.CharField(default='-', max_length=255, verbose_name='\u5e74\u85aa(\u4e07\u5143)')),
                ('chiguzonge', models.CharField(default='-', max_length=255, verbose_name='\u6301\u80a1\u603b\u989d(\u4e07\u5143)')),
                ('chigushuliang', models.CharField(default='-', max_length=255, verbose_name='\u6301\u80a1\u6570\u91cf(\u4e07\u80a1)')),
            ],
        ),
        migrations.RemoveField(
            model_name='gaoguan_info',
            name='name',
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='chigushuliang',
            field=models.CharField(default='-', max_length=255, verbose_name='\u6301\u80a1\u6570\u91cf(\u4e07\u80a1)'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='chiguzonge',
            field=models.CharField(default='-', max_length=255, verbose_name='\u6301\u80a1\u603b\u989d(\u4e07\u5143)'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='company_code',
            field=models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='dongjiangao',
            field=models.CharField(default='-', max_length=255, verbose_name='\u8463\u76d1\u9ad8\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='gaoguanzhiwu',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9ad8\u7ba1\u804c\u52a1'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='lizhiriqi',
            field=models.CharField(default='-', max_length=255, verbose_name='\u79bb\u804c\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='nianxin',
            field=models.CharField(default='-', max_length=255, verbose_name='\u5e74\u85aa(\u4e07\u5143)'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='renzhiriqi',
            field=models.CharField(default='-', max_length=255, verbose_name='\u4efb\u804c\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='gaoguan_info',
            name='xueli',
            field=models.CharField(default='-', max_length=255, verbose_name='\u5b66\u5386'),
        ),
    ]
