# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexun', '0003_auto_20170411_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fenhong_Huigou_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801')),
                ('gonggaoshijian', models.CharField(default='-', max_length=255, verbose_name='\u516c\u544a\u65f6\u95f4')),
                ('huigouzanzonggubenbili', models.CharField(default='-', max_length=255, verbose_name='\u56de\u8d2d\u5360\u603b\u80a1\u672c\u6bd4\u4f8b%')),
                ('huigougushu', models.CharField(default='-', max_length=255, verbose_name='\u56de\u8d2d\u80a1\u6570(\u80a1)')),
                ('nihuigoujiage', models.CharField(default='-', max_length=255, verbose_name='\u62df\u56de\u8d2d\u4ef7\u683c(\u5143)')),
                ('gonggaoqianrigujia', models.CharField(default='-', max_length=255, verbose_name='\u516c\u544a\u524d\u65e5\u80a1\u4ef7(\u5143)')),
                ('goumaizuigaojia', models.CharField(default='-', max_length=255, verbose_name='\u8d2d\u4e70\u6700\u9ad8\u4ef7(\u5143)')),
                ('goumaizuidijia', models.CharField(default='-', max_length=255, verbose_name='\u8d2d\u4e70\u6700\u4f4e\u4ef7(\u5143)')),
                ('huigouzongjine', models.CharField(default='-', max_length=255, verbose_name='\u56de\u8d2d\u603b\u91d1\u989d(\u4e07\u5143)')),
                ('shifoshisi', models.CharField(default='-', max_length=255, verbose_name='\u662f\u5426\u5b9e\u65bd')),
                ('xiangqing', models.CharField(default='-', max_length=255, verbose_name='\u5206\u7ea2\u8be6\u60c5')),
            ],
        ),
        migrations.CreateModel(
            name='Fenhong_Peigu_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801')),
                ('gonggaoshijian', models.CharField(default='-', max_length=255, verbose_name='\u516c\u544a\u65f6\u95f4')),
                ('peigufangan', models.CharField(default='-', max_length=255, verbose_name='\u914d\u80a1\u65b9\u6848(\u80a1/10\u80a1)')),
                ('peigujia', models.CharField(default='-', max_length=255, verbose_name='\u914d\u80a1\u4ef7(\u5143)')),
                ('jizhunguben', models.CharField(default='-', max_length=255, verbose_name='\u57fa\u51c6\u80a1\u672c(\u4e07\u80a1)')),
                ('chuquanri', models.CharField(default='-', max_length=255, verbose_name='\u9664\u6743\u65e5')),
                ('guquandengjiri', models.CharField(default='-', max_length=255, verbose_name='\u80a1\u6743\u767b\u8bb0\u65e5')),
                ('jiaokuanqishiri', models.CharField(default='-', max_length=255, verbose_name='\u7f34\u6b3e\u8d77\u59cb\u65e5')),
                ('jiaokuanzhongzhiri', models.CharField(default='-', max_length=255, verbose_name='\u7f34\u6b3e\u7ec8\u6b62\u65e5')),
                ('peigushangshiri', models.CharField(default='-', max_length=255, verbose_name='\u914d\u80a1\u4e0a\u5e02\u65e5')),
                ('mujizijin', models.CharField(default='-', max_length=255, verbose_name='\u52df\u96c6\u8d44\u91d1\u5408\u8ba1(\u5143)')),
                ('xiangqing', models.CharField(default='-', max_length=255, verbose_name='\u5206\u7ea2\u8be6\u60c5')),
            ],
        ),
        migrations.CreateModel(
            name='Fenhong_Zhuanzeng_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801')),
                ('gonggaoshijian', models.CharField(default='-', max_length=255, verbose_name='\u516c\u544a\u65f6\u95f4')),
                ('zhuanzeng', models.CharField(default='-', max_length=255, verbose_name='\u8f6c\u589e(\u80a1/10\u80a1)')),
                ('chuquanchuxiri', models.CharField(default='-', max_length=255, verbose_name='\u9664\u6743\u9664\u606f\u65e5')),
                ('chuquandengjiri', models.CharField(default='-', max_length=255, verbose_name='\u9664\u6743\u767b\u8bb0\u65e5')),
                ('zhuanzenggushangshiri', models.CharField(default='-', max_length=255, verbose_name='\u8f6c\u589e\u80a1\u4e0a\u5e02\u65e5')),
                ('tongqisonggu', models.CharField(default='-', max_length=255, verbose_name='\u540c\u671f\u9001\u80a1(\u80a1/10\u80a1)')),
                ('fanganjianjie', models.CharField(default='-', max_length=255, verbose_name='\u65b9\u6848\u7b80\u4ecb')),
                ('shifoshisi', models.CharField(default='-', max_length=255, verbose_name='\u662f\u5426\u5b9e\u65bd')),
                ('xiangqing', models.CharField(default='-', max_length=255, verbose_name='\u5206\u7ea2\u8be6\u60c5')),
            ],
        ),
        migrations.RemoveField(
            model_name='fenhong_info',
            name='time',
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='company_code',
            field=models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='gonggaoshijian',
            field=models.CharField(default='-', max_length=255, verbose_name='\u516c\u544a\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='guquanchuxiri',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9664\u6743\u9664\u606f\u65e5'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='guquandengjiri',
            field=models.CharField(default='-', max_length=255, verbose_name='\u80a1\u6743\u767b\u8bb0\u65e5'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='honggushangshiri',
            field=models.CharField(default='-', max_length=255, verbose_name='\u7ea2\u80a1\u4e0a\u5e02\u65e5'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='kuaijiniandu',
            field=models.CharField(default='-', max_length=255, verbose_name='\u4f1a\u8ba1\u5e74\u5ea6'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='paixi',
            field=models.CharField(default='-', max_length=255, verbose_name='\u6d3e\u606f(\u5143/10\u80a1)'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='shifoshisi',
            field=models.CharField(default='-', max_length=255, verbose_name='\u662f\u5426\u5b9e\u65bd'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='songgu',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9001\u80a1(\u80a1/10\u80a1)'),
        ),
        migrations.AddField(
            model_name='fenhong_info',
            name='xiangqing',
            field=models.CharField(default='-', max_length=255, verbose_name='\u5206\u7ea2\u8be6\u60c5'),
        ),
    ]
