# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexun', '0004_auto_20170411_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showrufenbu_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='-', max_length=255, verbose_name='\u516c\u53f8\u80a1\u7968\u4ee3\u7801')),
                ('leibiemingcheng', models.CharField(default='-', max_length=255, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('yinyeshouru', models.CharField(default='-', max_length=255, verbose_name='\u8425\u4e1a\u6536\u5165(\u4e07\u5143)')),
                ('zhanyinyeshourubili', models.CharField(default='-', max_length=255, verbose_name='\u5360\u8425\u4e1a\u6536\u5165\u6bd4\u4f8b(%)')),
                ('yinyechengben', models.CharField(default='-', max_length=255, verbose_name='\u8425\u4e1a\u6210\u672c(\u4e07\u5143)')),
                ('zhanchengbenbili', models.CharField(default='-', max_length=255, verbose_name='\u5360\u6210\u672c\u6bd4\u4f8b')),
                ('yingyelirun', models.CharField(default='-', max_length=255, verbose_name='\u8425\u4e1a\u5229\u6da6(\u4e07\u5143)')),
                ('zhanlirunbili', models.CharField(default='-', max_length=255, verbose_name='\u5360\u5229\u6da6\u6bd4\u4f8b')),
                ('maolilv', models.CharField(default='-', max_length=255, verbose_name='\u6bdb\u5229\u7387(%)')),
            ],
        ),
    ]
