# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hightechinfo',
            old_name='url',
            new_name='number',
        ),
    ]
