# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0003_unit_annual_promoters_and_reports_investment_infor_unit_annual_reports_base_infor_unit_annual_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit_annual_Promoters_and_reports_investment_Infor',
            new_name='Unit_annual_Promoters_and_reports_investment_Info',
        ),
        migrations.RenameModel(
            old_name='Unit_annual_reports_Base_Infor',
            new_name='Unit_annual_reports_Base_Info',
        ),
        migrations.RenameModel(
            old_name='Unit_annual_reports_Website_Infor',
            new_name='Unit_annual_reports_Website_Info',
        ),
        migrations.RenameModel(
            old_name='Unit_Base_Info_Changed_Information',
            new_name='Unit_Base_Info_Changed_Info',
        ),
        migrations.RenameModel(
            old_name='Unit_Base_Info_Shareholder_Information',
            new_name='Unit_Base_Info_Shareholder_Info',
        ),
        migrations.RenameField(
            model_name='unit_annual_reports_base_info',
            old_name='investment_information',
            new_name='investment_Info',
        ),
        migrations.AlterField(
            model_name='hightechinfo',
            name='number',
            field=models.IntegerField(max_length=255, verbose_name='\u5e8f\u53f7'),
        ),
    ]
