# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0004_auto_20170227_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_base_info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='unit_base_info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='unit_base_info',
            name='website',
        ),
    ]
