# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0007_auto_20170307_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc_base_info',
            name='Main_business',
            field=models.CharField(max_length=1024, verbose_name='\u4e3b\u8425\u4e1a\u52a1'),
        ),
    ]
