# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0008_auto_20170307_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc_base_info',
            name='Satisfaction',
            field=models.CharField(max_length=1024, verbose_name='\u6ee1\u610f\u5ea6'),
        ),
    ]
