# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0009_auto_20170307_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc_base_info',
            name='qicq',
            field=models.CharField(default='null', max_length=255, verbose_name='qq'),
        ),
    ]
