# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0011_auto_20170307_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itjuzi_Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_allname', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u5168\u540d')),
                ('company_name', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u540d')),
            ],
        ),
    ]
