# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0012_itjuzi_company_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itjuzi_company_info',
            name='company_allname',
            field=models.CharField(max_length=999, verbose_name='\u4f01\u4e1a\u5168\u540d'),
        ),
        migrations.AlterField(
            model_name='itjuzi_company_info',
            name='company_name',
            field=models.CharField(max_length=999, verbose_name='\u4f01\u4e1a\u540d'),
        ),
    ]
