# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0013_auto_20170316_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gao_Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_nunber', models.CharField(max_length=255, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('Enterprise_address', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u5730\u5740')),
                ('company_name', models.CharField(max_length=999, verbose_name='\u4f01\u4e1a\u5168\u540d')),
                ('Legal_representative', models.CharField(max_length=255, verbose_name='\u6cd5\u5b9a\u4ee3\u8868\u4eba')),
                ('Business_scope', models.CharField(max_length=255, verbose_name='\u7ecf\u8425\u8303\u56f4')),
                ('status', models.CharField(max_length=255, verbose_name='\u72b6\u6001')),
                ('category', models.CharField(max_length=255, verbose_name='\u5206\u7c7b')),
            ],
        ),
    ]
