# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hightech', '0014_gao_company_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_annual_promoters_and_reports_investment_info',
            name='Unit_id',
        ),
        migrations.RemoveField(
            model_name='unit_annual_reports_base_info',
            name='Unit_id',
        ),
        migrations.RemoveField(
            model_name='unit_annual_reports_website_info',
            name='Unit_id',
        ),
        migrations.RemoveField(
            model_name='unit_base_info',
            name='Unit_id',
        ),
        migrations.RemoveField(
            model_name='unit_base_info_changed_info',
            name='Unit_id',
        ),
        migrations.RemoveField(
            model_name='unit_base_info_shareholder_info',
            name='Unit_id',
        ),
        migrations.AddField(
            model_name='unit_annual_promoters_and_reports_investment_info',
            name='searched_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u67e5\u8be2\u5230\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_annual_promoters_and_reports_investment_info',
            name='searching_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9700\u8981\u67e5\u8be2\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_annual_reports_base_info',
            name='searched_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u67e5\u8be2\u5230\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_annual_reports_base_info',
            name='searching_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9700\u8981\u67e5\u8be2\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_annual_reports_website_info',
            name='searched_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u67e5\u8be2\u5230\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_annual_reports_website_info',
            name='searching_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9700\u8981\u67e5\u8be2\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_base_info',
            name='searched_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u67e5\u8be2\u5230\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_base_info',
            name='searching_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9700\u8981\u67e5\u8be2\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_base_info_changed_info',
            name='searched_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u67e5\u8be2\u5230\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_base_info_changed_info',
            name='searching_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9700\u8981\u67e5\u8be2\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_base_info_shareholder_info',
            name='searched_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u67e5\u8be2\u5230\u7684\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='unit_base_info_shareholder_info',
            name='searching_name',
            field=models.CharField(default='-', max_length=255, verbose_name='\u9700\u8981\u67e5\u8be2\u7684\u540d\u5b57'),
        ),
    ]
