# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='QiuShi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255, verbose_name='\u7f51\u7ad9\u5730\u5740')),
                ('user', models.CharField(max_length=255, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('content', models.CharField(max_length=255, verbose_name='\u6587\u5b57\u5185\u5bb9')),
                ('type', models.CharField(max_length=255, verbose_name='\u7c7b\u578b')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='\u56fe\u7247\u5185\u5bb9')),
                ('url0', models.CharField(blank=True, max_length=255, verbose_name='\u89c6\u9891\u5185\u5bb9')),
                ('smiling', models.IntegerField(verbose_name='\u7b11\u8138\u6570\u91cf')),
                ('comment_count', models.IntegerField(verbose_name='\u8bc4\u8bba\u6570\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('fans', models.IntegerField(verbose_name='\u7c89\u4e1d\u6570\u91cf')),
                ('follow', models.IntegerField(verbose_name='\u5173\u6ce8\u6570\u91cf')),
                ('comment', models.IntegerField(verbose_name='\u8bc4\u8bba\u6570\u91cf')),
                ('marriage', models.CharField(max_length=255, verbose_name='\u5a5a\u59fb\u72b6\u6001')),
                ('occupation', models.CharField(max_length=255, verbose_name='\u804c\u4e1a')),
                ('constellation', models.CharField(max_length=255, verbose_name='\u661f\u5ea7')),
                ('age', models.IntegerField(verbose_name='\u7cd7\u9f84')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='qiushi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentQishi', to='spiders.QiuShi'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentUser', to='spiders.User'),
        ),
    ]
