# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiushi',
            name='url0',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='\u89c6\u9891\u5185\u5bb9'),
        ),
    ]
