# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_auto_20160520_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=255, verbose_name='\u7cd7\u9f84'),
        ),
    ]
