# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0003_auto_20160520_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='qiushi',
        ),
        migrations.AddField(
            model_name='comment',
            name='qiushiURL',
            field=models.CharField(default=None, max_length=255, verbose_name='\u7cd7\u4e8bURL'),
        ),
    ]
