# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0004_auto_20160520_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qiushi',
            old_name='content',
            new_name='contents',
        ),
        migrations.AlterField(
            model_name='comment',
            name='qiushiURL',
            field=models.CharField(max_length=255, verbose_name='\u7cd7\u4e8bURL'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=255, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
    ]
