# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='\u6bcf\u6761\u65b0\u95fb\u7684\u771f\u5b9eURL')),
                ('md5', models.CharField(max_length=255, verbose_name='\u6bcf\u6761\u65b0\u95fb\u771f\u5b9eURL\u7684MD5')),
            ],
        ),
        migrations.CreateModel(
            name='Day_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='\u6bcf\u65e5\u65b0\u95fb\u771f\u5b9eURL')),
                ('md5', models.CharField(max_length=255, verbose_name='\u6bcf\u65e5\u65b0\u95fb\u771f\u5b9eURL\u7684MD5')),
            ],
        ),
        migrations.CreateModel(
            name='News_Real_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='nil', max_length=255, verbose_name='\u7f51\u5740')),
                ('title', models.CharField(default='nil', max_length=255, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('content', models.CharField(default='nil', max_length=255, verbose_name='\u65b0\u95fb\u5177\u4f53\u5185\u5bb9')),
                ('content_time', models.CharField(default='nil', max_length=255, verbose_name='\u65b0\u95fb\u65f6\u95f4')),
                ('content_from', models.CharField(default='nil', max_length=255, verbose_name='\u65b0\u95fb\u6765\u6e90')),
                ('content_type', models.CharField(default='\u6587\u5b57\u65b0\u95fb', max_length=255, verbose_name='\u65b0\u95fb\u7c7b\u578b')),
                ('content_web', models.CharField(default='\u6765\u6e90', max_length=255, verbose_name='\u65b0\u95fb\u722c\u53d6\u6765\u6e90')),
                ('save_time', models.CharField(default='nil', max_length=255, verbose_name='\u8bb0\u5f55\u722c\u53d6\u65f6\u95f4')),
                ('content_html', models.TextField(default='nil', max_length=1999, verbose_name='\u65b0\u95fb\u5177\u4f53\u5185\u5bb9\u6e90\u7801')),
            ],
        ),
    ]
