# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_real_content',
            name='content',
            field=models.TextField(default='nil', max_length=1999, verbose_name='\u65b0\u95fb\u5177\u4f53\u5185\u5bb9'),
        ),
    ]
