# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0002_auto_20161203_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='游戏', max_length=255, verbose_name='分类')),
            ],
        ),
        migrations.RemoveField(
            model_name='coser',
            name='category',
        ),
        migrations.DeleteModel(
            name='Coser_Category',
        ),
        migrations.AddField(
            model_name='category',
            name='coser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coser_Category', to='webapps.Coser'),
        ),
    ]
