# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anjuke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255, verbose_name='\u6240\u5728\u533a\u57df')),
                ('url', models.CharField(max_length=255, verbose_name='\u7f51\u7ad9\u5730\u5740')),
                ('image', models.CharField(max_length=255, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('saleprice', models.CharField(max_length=255, verbose_name='\u552e\u4ef7')),
                ('shoufu', models.CharField(max_length=255, verbose_name='\u9996\u4ed8')),
                ('monthpay', models.CharField(max_length=255, verbose_name='\u6708\u4ed8')),
                ('unit_price', models.CharField(max_length=255, verbose_name='\u5355\u4ef7 /m2')),
                ('quarters', models.CharField(max_length=255, verbose_name='\u6240\u5728\u5c0f\u533a')),
                ('position', models.CharField(max_length=255, verbose_name='\u4f4d\u7f6e')),
                ('apartment', models.CharField(max_length=255, verbose_name='\u6237\u578b')),
                ('area', models.CharField(max_length=255, verbose_name='\u9762\u79ef')),
                ('orientation', models.CharField(max_length=255, verbose_name='\u671d\u5411')),
                ('floor', models.CharField(max_length=255, verbose_name='\u697c\u5c42')),
                ('renovation', models.CharField(max_length=255, verbose_name='\u88c5\u4fee')),
                ('type', models.CharField(max_length=255, verbose_name='\u7c7b\u578b')),
                ('details', models.CharField(max_length=255, verbose_name='\u8be6\u7ec6\u8bf4\u660e')),
            ],
        ),
    ]
