# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anjuke',
            old_name='details',
            new_name='detail',
        ),
    ]
